### ISSUE TITLE
Migration fails with missing Redis connection

### ISSUE THREAD

**Issue by pixelbrackets** [agendav/agendav#265]
Running the migrations using `php agendavcli migrations:migrate` fails with the following error:

```
PHP Fatal error:  Uncaught RedisException: Connection refused in /var/www/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php:200
Stack trace:
#0 /var/www/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(200): Redis->connect('127.0.0.1')
#1 /var/www/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(147): Doctrine\ORM\Tools\Setup::createCacheInstance(false, NULL)
#2 /var/www/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(125): Doctrine\ORM\Tools\Setup::createCacheConfiguration(false, '/tmp', NULL)
#3 /var/www/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(71): Doctrine\ORM\Tools\Setup::createConfiguration(false, '/tmp', NULL)
#4 /var/www/web/app/services.php(34): Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration(Array, false)
#5 /var/www/web/vendor/pimple/pimple/src/Pimple/Container.php(118): {cl in /var/www/web/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php on line 200
```

The problem is: I dont have Redis enabled. And I cant stop agendav / Doctrine to try using it.

**Comment by pixelbrackets** [comment]
This thread described the save problem: https://community.open-emr.org/t/redis-connection-failed/10237

> It turns out if:
> 
> * PHP redis extension installed
> * And if there is no localhost redis server
> 
> Then doctrine throws an error, which is not an uncommon occurrence (for example, if using a redis server rather than on the same server as php server).

The proposed solution was to [enforce dev mode for `createAnnotationMetadataConfiguration()`](https://github.com/openemr/openemr/pull/1726/files)

When I did this to the method in `web/app/services.php`, the migration started.
